// Generated by CoffeeScript 1.3.3
(function() {
  var redraw, submit_text, submit_url;

  d3.select('#text_btn').on('click', submit_text);

  d3.select('#text_input').on('keyup', function() {
    if (d3.event.keyCode === 13) {
      return submit_text();
    }
  });

  submit_text = function() {
    var text;
    text = d3.select('#text_input').node().value;
    return d3.json('http://wafi.iit.cnr.it/multilingualweb/wli/api/identify').post(text, function(error, data) {
      if (error) {
        throw error;
      }
      console.log(data);
      return redraw(data);
    });
  };

  d3.select('#url_btn').on('click', submit_url);

  d3.select('#url_input').on('keyup', function() {
    if (d3.event.keyCode === 13) {
      return submit_url();
    }
  });

  submit_url = function() {
    var url;
    url = d3.select('#url_input').node().value;
    return d3.json('http://wafi.iit.cnr.it/multilingualweb/wli/api/retrieve+identify/' + url, function(data) {
      console.log(data);
      return redraw(data);
    });
  };

  redraw = function(data_obj) {
    var data, identifiers;
    data = Object.keys(data_obj).map(function(k) {
      data_obj[k].id = k;
      return data_obj[k];
    });
    identifiers = d3.select('#results').selectAll('.identifier').data(data, function(d) {
      return d.id;
    });
    identifiers.enter().append('li').attr({
      "class": 'identifier'
    });
    identifiers.classed('error', function(d) {
      return d.status !== 'ok';
    }).html(function(d) {
      if (d.status === 'ok') {
        return "<span class='identifier_name'>" + d.id + "</span><br>" + d.best + " (<span class='best'>" + d.best_name + "</span>) " + (d3.format('%')(d.result[d.best]));
      } else {
        return "<span class='identifier_name'>" + d.id + "</span>";
      }
    });
    return identifiers.exit().remove();
  };

}).call(this);
