// Generated by CoffeeScript 1.3.3
(function() {
  var refresh_results;

  refresh_results = function(data) {
    var all_node, identifier, identifier_node, lang, response, value, _results;
    _results = [];
    for (identifier in data) {
      response = data[identifier];
      identifier_node = $("<li></li>");
      $('#results').append(identifier_node);
      identifier_node.append($("<div class='identifier_name'>" + identifier + "</div>"));
      if (response.status === 'exception') {
        identifier_node.append($("<div>An exception occurred.</div>"));
        continue;
      }
      identifier_node.append($("<div>Best: <span class='best'>" + response.best + "</span> (" + (Math.round(response.result[response.best] * 100)) + "%)</div>"));
      all_node = $("<div></div>");
      identifier_node.append(all_node);
      all_node.append($("<span>All: </span>"));
      _results.push((function() {
        var _ref, _results1;
        _ref = response.result;
        _results1 = [];
        for (lang in _ref) {
          value = _ref[lang];
          _results1.push(all_node.append($("<span>" + lang + "(" + (Math.round(value * 100)) + "%) </span>")));
        }
        return _results1;
      })());
    }
    return _results;
  };

  $(function() {
    var _this = this;
    $('body').append(new fk.TextInput({
      id: 'url_box',
      input_id: 'url_input',
      label: 'http://',
      submit_btn: new fk.Button({
        label: 'Identify'
      })
    })).append(new fk.TextInput({
      id: 'text_box',
      input_id: 'text_input',
      label: 'Text:',
      submit_btn: new fk.Button({
        label: 'Identify'
      })
    })).append($("<ul class='_box _flex' id='results'></ul>"));
    $('#url_box').bind('submit', function(event, url) {
      $('#results').empty();
      return $.ajax({
        url: 'http://wafi.iit.cnr.it/multilingualweb/wli/api/retrieve+identify/' + url,
        method: 'GET',
        dataType: 'json',
        success: refresh_results
      });
    });
    return $('#text_box').bind('submit', function(event, text) {
      $('#results').empty();
      return $.ajax({
        url: 'http://wafi.iit.cnr.it/multilingualweb/wli/api/identify',
        method: 'POST',
        dataType: 'json',
        data: text,
        success: refresh_results
      });
    });
  });

}).call(this);
